### ISSUE TITLE
Deploy the built custom keycloak to a K8s cluster on AWS

### ISSUE THREAD

**Issue by ArmandMeppa** [adorsys/keycloak-ssi-deployment#2]
## What to be done
- [ ] Learn how to use the container service on AWS
- [ ] Deploy our keycloak with oid4vci on AWS
- [ ] Create a GitHub Action to continuously deploy the oid4vci keycloak image to k8s on AWS

**Comment by ArmandMeppa** [comment]
### DoD
- Have a working workflow for the continuous deployment
- The team should be able access the custom keycloak from their endpoints

**Comment by ArmandMeppa** [comment]
## Sync meeting with @francis-pouatcha on the 2024-02-14
### Points made clear 
- For the PoC we'll use a docker container to deploy our keycloak image
- The docker image of our custom keycloak will be made public so that anyone can use it
- The final version of the Datev project will use our custom keycloak

### Points we need more clarification
- We need to know if the whole Datev project will be deployed on a k8s cluster or not. From that we'll decide to use it or not

**Comment by bengo237** [comment]
faces issue with "HTTPS REQUIRED" , after reseach we can disable https while trying to connect externally or  Include TLS/SSL certificate generation in our cd pipeline to have a secured connection to our deployed docker image.
we choose procceed with the TLS/SSL certificate 

## Deactivate SSL/TLS for Keycloak Container

To deactivate SSL/TLS, follow the steps below:

1. Enter the container in interactive mode:
    ```bash
    docker exec -it keycloak-dev bash
    ```

2. Set the path to use the `kcadm.sh` script:
    ```ruby
    export PATH=$PATH:/opt/keycloak/bin
    ```

3. Configure credentials for the server and user of the master realm:
    ```arduino
    kcadm.sh config credentials --server http://localhost:8080/ \
      --realm master \
      --user admin --password <your_password>
    ```

4. Get the realm details outputted in JSON format to verify SSL/TLS configuration:
    ```arduino
    kcadm.sh get realms/master
    ```

    You'll see that the value for `sslRequired` is set to `external`, indicating that SSL/TLS is required outside of our VPC.

5. Disable the SSL/TLS requirement for the master realm:
    ```sql
    kcadm.sh update realms/master -s enabled=true -s sslRequired=none
    ```

6. Now, revisit the "Administration Console" on your browser. This time, the login page should appear without SSL/TLS requirements.

**Note:** Ensure to replace `<your_password>` with your actual admin password.

## Setting Up TLS/SSL certificate
First we have to update our Dockerfile  and add the step inside

**Comment by francis-pouatcha** [comment]
- Self Signed Certificate generated with Stephane today.
- Attempted to use AWS, but no zone was available for the purpose.
- Load balancer created. Manages external SSL connection.
- Internal connection between load balancer an keycloak still untrusted.

**Comment by nitch2019** [comment]
@ArmandMeppa please share yout thoughts and questions here for @francis-pouatcha

**Comment by ArmandMeppa** [comment]
Hello sir @francis-pouatcha, we had a meeting with @stephane-segning regarding the deployment architecture of Keycloak on AWS for the POC, we came up with 2 options:
1- Pass the SSL certificates directly when building the image, which is not a good practice but will take less time.
2- Have a custom domain/subdomain for us, use AWS ACM to provision the SSL certificates and pass them at the end of the workflow when we want to launch the service. It will be more expensive but more secure.
Do we want a working version of KCOID4VCI or do we want to implement the best practices already in this POC?

**Comment by bengo237** [comment]
need to know how to proceed, as the Keycloak deployment requires HTTPS. Continue with the self-signed certificate or request a certificate from the Certificate Authority and for this we need a valid domain name or subdomain.

**Comment by nitch2019** [comment]
Sync with Yannick

**Comment by nitch2019** [comment]
Request for domain name has been submitted and is ongoing

**Comment by hugoib** [comment]
It is not closed: In progress, IT is providing further needed things.

**Comment by nitch2019** [comment]
Subdomain has been provided. 
Security issues has been fixed.

**Comment by nitch2019** [comment]
The Proxy is finisched .
The are still some fix to resolved
